global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'gateway-service'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway:8080' ]
  - job_name: 'authorization-service'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'authorization-service:8083' ]
